### ISSUE TITLE
LB 3/3 Number of auto-regressive terms

### ISSUE THREAD

**Issue by orlandocosta76** [LDSSA/batch2-BLU02#2]
Hi, in the 3rd notebook there is this code:
```
model = ARIMA(sales_logged_diff.dropna().values, order=(1, 0, 0))
results = model.fit();
```
but later text says:
`We passed the order (p, d, q) as (3, 0, 0), as we'd established that we want to try p=3`

So which one was to be used? I am also confused because looking at the autocorrelation graph, I would say 6 would be the value to try first (because it is the first crossing the significance frontier),  is it not?

Also, I think it would be nice a comment about the plot of ARIMA, after the code:
```
results.plot_predict()
plt.show()
```

**Comment by hershaw** [comment]
good catch! fixed and many thanks!

**Comment by orlandocosta76** [comment]
@hershaw 
1. I am still confused with why choosing the value of p=1,  because looking at the auto-correlation graph, I would say 6 would be the value to try first (because it is the first crossing the significance line), is it not? Or is there something I am missing? 

2. In the text it says _"A rule of thumb is to start by testing the number of components where the significance line gets crossed, and make that our p. This example was chosen quite deliberately to show that sometimes this doesn't actually happen, and that sometimes these cases are a lot more ambiguous.
So we have no guarantees that the data contains an AR process (there is some indication it doesn't) "_

So, it seems the significance line is crossed at p=6, as said above, and not sure about the meaning of the last sentence, why is there an indication the data does not contain an AR process? Because the significance line is flat and constant?
